### ISSUE TITLE
Conference in two physical locations

### ISSUE THREAD

**Issue by kedlaya** [nilesjohnson/conference-list#79]
I'm starting to see something new on MathMeetings: postings about conferences being held in two physical locations (often in different countries) via a videoconference link. Between travel restrictions (hopefully temporary) and climate concerns (probably less so) this category is likely to grow going forward.

Right now there is no satisfactory way to specify this: some organizers are choosing one of the two countries, as in

https://mathmeetings.net/conferences/view/1098

while some are doing separate entries for the two locations, as in

https://mathmeetings.net/conferences/view/1093
https://mathmeetings.net/conferences/view/1094

But I'm guessing the server database is not set up to treat location as a multivalued function?

**Comment by nilesjohnson** [comment]
I've added "Online" as an option, but I'm still not sure how to handle the multiple (physical) location issue.  I can think of three options:

- Since the "City" field accepts arbitrary text, additional locations could be put there, and the country set to "(Multiple)" or something like that.
- Add a database field "additional_locations"
- Add a new table for countries, and then change the conferences database to reference it, with a multivalued option

Of these, the last one sounds like too much overhaul, but either of the first two sounds doable.  Both require a change to the "New Announcement" form, and that might be the only nontrivial work to do in either case.
