### ISSUE TITLE
Data sanitization in City field

### ISSUE THREAD

**Issue by kedlaya** [nilesjohnson/conference-list#86]
I just observed this example that broke my front end: the API was generating a line of the form
```
<title>Workshop on Number Theory in Function Fields </title><link>http://sites.google.com/view/workshoponntinff</link><guid isPermaLink="true">http://sites.google.com/view/workshoponntinff</guid><enclosure url="https://mathmeetings.net/conferences/view/1610.ics" length="236" type="text/calendar"/>
```
missing the <description> tag. The problem was that someone had done a bad copy-paste into the City field so that there was an initial non-ASCII character; removing it solved the problem, but of course it would be better to user-proof against this effect.

**Comment by nilesjohnson** [comment]
Thanks for letting me know about this, but I haven't been able to figure out what the issue is.  To try to figure out why that one particular character is an issue, I made an entry on the test site

https://test.mathmeetings.net/conferences/view/1118

by copy/pasting the character from my copy of the first confirmation email for that conference.  Then I did some testing, and here's what I can tell so far:

- The main list at https://test.mathmeetings.net doesn't seem to be affected.
- My demo javascript front end doesn't seem to be affected (https://nilesjohnson.net/testmmnet.html).
(Note, that front end doesn't list the city, but I also put the unknown character in the title,)
- When I point your python front end at the test site, I *do* see the error you mentioned.
- When I use your front end, but restrict to the at.json subject, then the list loads fine, including the other entry testing unicode and emoji in titles.

So, what does this mean?  I thought maybe your python front end was having trouble with non-ascii characters, but it seems to deal with others just fine.  At the same time, the javascript front end demo, and the more general mmnet webserver, don't seem to have trouble with the other character.  (I don't know *what* type of character it is either; it appears to be some kind of space, but I don't know how to tell.)

As a guess, maybe that particular character is somehow tripping up the regular expressions in your cgi script?  If you have any other guesses, please let me know.  I'm also happy to add some filtering on the mmnet side, but at this point I don't know *what* to filter (other than, I guess, that one specific character).  I would prefer to keep unicode compatibility if possible.

**Comment by nilesjohnson** [comment]
great; this seems to resolve the issues here!
